# source: rosepinetheme.com

$base           = rgb(191724)
$surface        = rgb(1f1d2e)
$overlay        = rgb(26233a)
$muted          = rgb(6e6a86)
$subtle         = rgb(908caa)
$text           = e0def4
$love           = eb6f92
$gold           = rgb(f6c177)
$rose           = rgb(ebbcba)
$pine           = rgb(31748f)
$foam           = rgb(9ccfd8)
$iris           = rgb(c4a7e7)
$highlightLow   = rgb(21202e)
$highlightMed   = rgb(403d52)
$highlightHigh  = rgb(524f67)

$background = $base
$foreground = rgb($text)
$foreground_alpha = $text
$primary = rgb($love)
$primary_alpha = $love

env = XCURSOR_THEME,BreezeX-RosePineDawn
env = XCURSOR_SIZE,48

env = HYPRCURSOR_THEME,rose-pine-dawn-hyprcursor
env = HYPRCURSOR_SIZE,48

env = GTK_THEME,RosePine

