[general]
live_config_reload = false
import = [ "~/.config/alacritty/theme.toml" ]

[window]
dimensions = { columns = 64, lines = 24 }
padding = { x = 0, y = 0 }

[font]
normal = { family = "GoMono Nerd Font" }
size = 12

[cursor]
style = { shape = "Block", blinking = "On" }
[mouse]
hide_when_typing= true

