# PORTAGE MAKE.CONF

## Pre-ops
LC_MESSAGES=C.UTF-8
ACCEPT_LICENSE="*"
L10N="en_AU"
GENTOO_MIRRORS="https://mirror.freedif.org/gentoo \
    https://mirror.planetunix.net/pub/gentoo/ \
    https://gentoo.kurdy.org/ \
    https://mirror.keiminem.com/gentoo/"

### Flag
_USE_BASIC_HUMAN_RIGHTS="-telemetry -geolocation -test -debug"
_USE_HOST="dist-kernel rust clang lto -systemd openrc elogind dbus udev libnotify"
_USE_USERSPACE="X wayland -kde -qt5 -qt6 -gnome imagemagick"
_USE_GRAPHICS="opengl vulkan sdl"
_USE_HWACCEL="vaapi opencl cuda nvenc"
_USE_MEDIA="ffmpeg x264 cairo"
_USE_AUDIO="pulseaudio alsa opus lame ogg vorbis"
USE="${_USE_BASIC_HUMAN_RIGHTS} ${_USE_HOST} ${_USE_USERSPACE} ${_USE_GRAPHICS} ${_USE_HWACCEL} ${_USE_MEDIA} ${_USE_AUDIO}"
VIDEO_CARDS="intel nvidia"

INSTALL_MASK="INSTALL.gz TODO.gz"
PORTAGE_TMPDIR="/var/tmp"

### Toolchain
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

### Log
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_ELOG_CLASSES="log warn error"
PORTAGE_ELOG_SYSTEM="echo save"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

### Tuning
PORTAGE_RSYNC_RETRIES="4"
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --jobs=4 --load-average=8 --keep-going"
MAKEOPTS="--jobs=12 --load-average=8"
AUTOCLEAN="yes"
