# PORTAGE MAKE.CONF

## Pre-ops
LC_MESSAGES=C.UTF-8
ACCEPT_LICENSE="*"
L10N="en_AU"
GENTOO_MIRRORS="https://mirror.freedif.org/gentoo \
    https://mirror.planetunix.net/pub/gentoo/ \
    https://gentoo.kurdy.org/ \
    https://mirror.keiminem.com/gentoo/"

### Flag

U_BASIC="-debug -examples -doc -profile -cups minimal -verify-sig -verify-provenance"

u_protection="-hardened -modules-sign -secureboot"
U_KERNEL="${u_protection} initramfs firmware dracut modules-compress symlink strip experimental"

U_SYSTEM="zstd clang lto openrc logind elogind dbus policykit udev libnotify"

u_networking="network -netifrc networkmanager -bluetooth -nas ssl"
U_DESKTOP="${u_networking} X wayland -kde qt5 qt6 -gnome gtk gtk3 -flatpak icu tray"

VIDEO_CARDS="intel nvidia"
U_GFX="opengl vulkan sdl"
U_HWACCEL="vaapi opencl cuda nvenc"

u_media_ext="png jpg jpeg xml svg tiff webp gif mp4"
U_MEDIA="${u_media_ext} ffmpeg imagemagick exif x264 cairo text harfbuzz minizip"

u_audio_ext="opus lame ogg vorbis aac"
U_AUDIO="${u_audio_ext} pulseaudio pipewire alsa pipewire-alsa wireplumber sound-server"

u_python="python_single_target_python3_13 -python_single_target_python3_14 python_targets_python3_13 python_targets_python3_14 python_targets_python3_15"
USE="${u_python} ${U_BASIC} ${U_KERNEL} ${U_SYSTEM} ${U_DESKTOP} ${U_GFX} ${U_HWACCEL} ${U_MEDIA} ${U_AUDIO}"

INSTALL_MASK="INSTALL.gz TODO.gz"
PORTAGE_TMPDIR="/var/tmp"

### Toolchain
COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

### Log
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_ELOG_CLASSES="log warn error"
PORTAGE_ELOG_SYSTEM="echo save"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

### Tuning
PORTAGE_RSYNC_RETRIES="4"
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --jobs=4 --load-average=8 --keep-going"
MAKEOPTS="--jobs=12 --load-average=8"
AUTOCLEAN="yes"
