# PORTAGE MAKE.CONF

## Pre-ops
LC_MESSAGES=C.UTF-8
ACCEPT_LICENSE="*"
L10N="en_AU"
GENTOO_MIRRORS="https://mirror.freedif.org/gentoo \
    https://mirror.planetunix.net/pub/gentoo/ \
    https://gentoo.kurdy.org/ \
    https://mirror.keiminem.com/gentoo/"

### Flag
U_BASIC="-debug -examples -doc -static-libs -profile -cups minimal ssl verify-sig verify-provenance"
U_KERNEL="dist-kernel -hardened initramfs modules-sign modules-compress savedconfig -secureboot strip experimental symlink"
U_SYSTEM="zstd rust clang lto openrc elogind dbus policykit udev libnotify"
U_DESKTOP="X wayland -bluetooth -kde qt5 qt6 -gnome gtk gtk3 imagemagick flatpak"
U_GFX="opengl vulkan sdl"
U_HWACCEL="vaapi opencl cuda nvenc"
U_MEDIA="ffmpeg exif x264 cairo png jpg jpeg gif tiff webp mp4 text minizip"
U_AUDIO="pulseaudio pipewire alsa pipewire-alsa wireplumber opus lame ogg vorbis aac sound-server"
USE="${U_BASIC} ${U_KERNEL} ${U_SYSTEM} ${U_DESKTOP} ${U_GFX} ${U_HWACCEL} ${U_MEDIA} ${U_AUDIO}"
VIDEO_CARDS="intel nvidia"

INSTALL_MASK="INSTALL.gz TODO.gz"
PORTAGE_TMPDIR="/var/tmp"

### Toolchain
COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

### Log
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_ELOG_CLASSES="log warn error"
PORTAGE_ELOG_SYSTEM="echo save"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

### Tuning
PORTAGE_RSYNC_RETRIES="4"
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --jobs=4 --load-average=8 --keep-going"
MAKEOPTS="--jobs=12 --load-average=8"
AUTOCLEAN="yes"
