# THIS IS A /etc/portage/make.conf FILE
# FOR Zentaro's MARCH_NATIVE

# PRE-OPTS
LC_MESSAGES=C.UTF-8
ACCEPT_LICENSE="*"
L10N="en_AU"
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"


EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --verbose --jobs=6 --load-average=12"

# ABI_X86="32 64"
USE="${USE}
	# dist-kernel
	openrc elogind dbus
	X wayland libnotify
	nvenc vulkan opengl
	opencl cuda
	pulseaudio alsa opus lame vorbis
	v4l vaapi x264 x265 vpx
	cairo lcms
	-kde -qt5 -qt6 -gnome gtk
	-telemetry
"
