COMMON_FLAGS="-O3 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

LC_MESSAGES=C.UTF-8
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --jobs=2 --load-average=4"

ACCEPT_LICENSE="*"

# ABI_X86="32 64"
USE="${USE} dist-kernel
	openrc elogind dbus networkmanager
	X wayland libnotify
	nvenc opengl vulkan cuda opencl
	pulseaudio alsa opus lame vorbis
	v4l vaapi x264 vpx
	cairo lcms
	-kde -qt5 -qt6 -gnome gtk"
L10N="en_AU"
