_BOOT_DIR='/boot'
_TEMP_DIR='/tmp'

# My setup has gentoo-kernel-bin and zen-sources

_GENTOO_KERNEL_VERSION="7.0.3"
_GENTOO_KERNEL="${_GENTOO_KERNEL_VERSION}-gentoo-dist"
_GENTOO_KERNEL_DIR="${_BOOT_DIR}/kernels-gentoo"

_ZEN_KERNEL_VERSION="7.0.3"
_ZEN_KERNEL="${_ZEN_KERNEL_VERSION}-zen1"
_ZEN_KERNEL_DIR="${_BOOT_DIR}/kernels-zen"
