# THIS IS AN ENVIRONMENT VARIABLE FILE
# FOR KERNEL INSIDE BOOT PARITION

_BOOT_DIR='/boot'

_GENTOO_KERNEL_DIR="${_BOOT_DIR}/kernels-gentoo"
_GENTOO_KERNEL_VERSION='7.0.5'
_GENTOO_KERNEL="${_GENTOO_KERNEL_VERSION}-gentoo-dist"

_ZEN_KERNEL_DIR="${_BOOT_DIR}/kernels-zen"
_ZEN_KERNEL_VERSION='7.0.5'
_ZEN_KERNEL="${_ZEN_KERNEL_VERSION}-zen1"

